// Auto-generated by update-characters.js

const characterData = [
  {
    "id": "24921505",
    "name": "Mira Wa'neko",
    "world": "Diabolos [Crystal]",
    "image": "https://img2.finalfantasyxiv.com/f/7c13a0269a6d7953946aff5be6ecff69_7b33d33ae3ecb996f778a5f67a6a0af6fl0.jpg?1768586024",
    "jobs": {
      "combat": [
        {
          "name": "Gunbreaker",
          "level": 100,
          "abbr": "GNB"
        },
        {
          "name": "White Mage",
          "level": 100,
          "abbr": "WHM"
        },
        {
          "name": "Scholar",
          "level": 100,
          "abbr": "SCH"
        },
        {
          "name": "Astrologian",
          "level": 100,
          "abbr": "AST"
        },
        {
          "name": "Sage",
          "level": 100,
          "abbr": "SGE"
        },
        {
          "name": "Dragoon",
          "level": 100,
          "abbr": "DRG"
        },
        {
          "name": "Ninja",
          "level": 100,
          "abbr": "NIN"
        },
        {
          "name": "Reaper",
          "level": 100,
          "abbr": "RPR"
        },
        {
          "name": "Viper",
          "level": 100,
          "abbr": "VPR"
        },
        {
          "name": "Dancer",
          "level": 100,
          "abbr": "DNC"
        },
        {
          "name": "Summoner",
          "level": 100,
          "abbr": "SMN"
        },
        {
          "name": "Red Mage",
          "level": 100,
          "abbr": "RDM"
        },
        {
          "name": "Pictomancer",
          "level": 100,
          "abbr": "PCT"
        },
        {
          "name": "Black Mage",
          "level": 96,
          "abbr": "BLM"
        },
        {
          "name": "Bard",
          "level": 83,
          "abbr": "BRD"
        },
        {
          "name": "Blue Mage",
          "level": 70,
          "abbr": "BLU"
        },
        {
          "name": "Samurai",
          "level": 50,
          "abbr": "SAM"
        },
        {
          "name": "Paladin",
          "level": 31,
          "abbr": "PLD"
        },
        {
          "name": "Pugilist",
          "level": 21,
          "abbr": "PGL"
        },
        {
          "name": "Marauder",
          "level": 11,
          "abbr": "MRD"
        },
        {
          "name": "Dark Knight",
          "level": 0,
          "abbr": "DRK"
        },
        {
          "name": "Machinist",
          "level": 0,
          "abbr": "MCH"
        }
      ],
      "crafters": [
        {
          "name": "Carpenter",
          "level": 100,
          "abbr": "CRP"
        },
        {
          "name": "Blacksmith",
          "level": 100,
          "abbr": "BSM"
        },
        {
          "name": "Armorer",
          "level": 100,
          "abbr": "ARM"
        },
        {
          "name": "Goldsmith",
          "level": 100,
          "abbr": "GSM"
        },
        {
          "name": "Leatherworker",
          "level": 100,
          "abbr": "LTW"
        },
        {
          "name": "Weaver",
          "level": 100,
          "abbr": "WVR"
        },
        {
          "name": "Alchemist",
          "level": 100,
          "abbr": "ALC"
        },
        {
          "name": "Culinarian",
          "level": 100,
          "abbr": "CUL"
        }
      ],
      "gatherers": [
        {
          "name": "Miner",
          "level": 100,
          "abbr": "MIN"
        },
        {
          "name": "Botanist",
          "level": 100,
          "abbr": "BTN"
        },
        {
          "name": "Fisher",
          "level": 100,
          "abbr": "FSH"
        }
      ],
      "phantom": [
        {
          "name": "Phantom Freelancer",
          "level": 10,
          "abbr": "Freelancer"
        },
        {
          "name": "Phantom Knight",
          "level": 6,
          "abbr": "Knight"
        },
        {
          "name": "Phantom Monk",
          "level": 6,
          "abbr": "Monk"
        },
        {
          "name": "Phantom Cannoneer",
          "level": 6,
          "abbr": "Cannoneer"
        },
        {
          "name": "Phantom Time Mage",
          "level": 5,
          "abbr": "Time Mage"
        },
        {
          "name": "Phantom Oracle",
          "level": 5,
          "abbr": "Oracle"
        },
        {
          "name": "Phantom Chemist",
          "level": 4,
          "abbr": "Chemist"
        },
        {
          "name": "Phantom Bard",
          "level": 4,
          "abbr": "Bard"
        },
        {
          "name": "Phantom Dancer",
          "level": 4,
          "abbr": "Dancer"
        },
        {
          "name": "Phantom Berserker",
          "level": 3,
          "abbr": "Berserker"
        },
        {
          "name": "Phantom Geomancer",
          "level": 3,
          "abbr": "Geomancer"
        },
        {
          "name": "Phantom Thief",
          "level": 1,
          "abbr": "Thief"
        },
        {
          "name": "Phantom Ranger",
          "level": 1,
          "abbr": "Ranger"
        },
        {
          "name": "Phantom Mystic Knight",
          "level": 1,
          "abbr": "Mystic Knight"
        },
        {
          "name": "Phantom Gladiator",
          "level": 1,
          "abbr": "Gladiator"
        }
      ]
    },
    "achievements": {
      "allScore": 16080,
      "baseScore": 15145,
      "relics": {
        "weapons": {
          "arr": {
            "name": "Zodiac Weapons",
            "abbr": "Zodiac",
            "expansion": "A Realm Reborn",
            "completed": 7,
            "total": 13,
            "percentage": 54,
            "highestStage": "Zodiac Zeta",
            "stages": [
              {
                "index": 0,
                "name": "Zodiac Zeta",
                "completed": 1,
                "total": 1,
                "percentage": 100
              },
              {
                "index": 1,
                "name": "Zodiac",
                "completed": 1,
                "total": 1,
                "percentage": 100
              },
              {
                "index": 2,
                "name": "Nexus",
                "completed": 1,
                "total": 1,
                "percentage": 100
              },
              {
                "index": 3,
                "name": "Novus",
                "completed": 1,
                "total": 1,
                "percentage": 100
              },
              {
                "index": 4,
                "name": "Animus",
                "completed": 1,
                "total": 1,
                "percentage": 100
              },
              {
                "index": 5,
                "name": "Zodarc",
                "completed": 7,
                "total": 13,
                "percentage": 54
              }
            ],
            "inProgress": true,
            "isComplete": false
          },
          "hw": {
            "name": "Anima Weapons",
            "abbr": "Anima",
            "expansion": "Heavensward",
            "completed": 1,
            "total": 13,
            "percentage": 8,
            "highestStage": "Lux",
            "stages": [
              {
                "index": 0,
                "name": "Lux",
                "completed": 1,
                "total": 13,
                "percentage": 8
              },
              {
                "index": 1,
                "name": "Complete",
                "completed": 1,
                "total": 13,
                "percentage": 8
              },
              {
                "index": 2,
                "name": "Sharpened",
                "completed": 1,
                "total": 13,
                "percentage": 8
              },
              {
                "index": 3,
                "name": "Reconditioned",
                "completed": 1,
                "total": 13,
                "percentage": 8
              },
              {
                "index": 4,
                "name": "Hyperconductive",
                "completed": 1,
                "total": 13,
                "percentage": 8
              },
              {
                "index": 5,
                "name": "Anima",
                "completed": 1,
                "total": 13,
                "percentage": 8
              }
            ],
            "inProgress": true,
            "isComplete": false
          },
          "sb": {
            "name": "Eureka Weapons",
            "abbr": "Eureka",
            "expansion": "Stormblood",
            "completed": 0,
            "total": 15,
            "percentage": 0,
            "highestStage": "Elemental",
            "stages": [
              {
                "index": 0,
                "name": "Eureka",
                "completed": 0,
                "total": 15,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Pyros",
                "completed": 0,
                "total": 15,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Elemental",
                "completed": 1,
                "total": 15,
                "percentage": 7
              },
              {
                "index": 3,
                "name": "Anemos",
                "completed": 1,
                "total": 15,
                "percentage": 7
              }
            ],
            "inProgress": true,
            "isComplete": false
          },
          "shb": {
            "name": "Resistance Weapons",
            "abbr": "Resistance",
            "expansion": "Shadowbringers",
            "completed": 1,
            "total": 17,
            "percentage": 6,
            "highestStage": "Blade's",
            "stages": [
              {
                "index": 0,
                "name": "Blade's",
                "completed": 1,
                "total": 17,
                "percentage": 6
              },
              {
                "index": 1,
                "name": "Law's Order",
                "completed": 2,
                "total": 17,
                "percentage": 12
              },
              {
                "index": 2,
                "name": "Recollection",
                "completed": 2,
                "total": 17,
                "percentage": 12
              },
              {
                "index": 3,
                "name": "Resistance",
                "completed": 4,
                "total": 17,
                "percentage": 24
              }
            ],
            "inProgress": true,
            "isComplete": false
          },
          "ew": {
            "name": "Manderville Weapons",
            "abbr": "Manderville",
            "expansion": "Endwalker",
            "completed": 11,
            "total": 19,
            "percentage": 58,
            "highestStage": "Mandervillous",
            "stages": [
              {
                "index": 0,
                "name": "Mandervillous",
                "completed": 11,
                "total": 19,
                "percentage": 58
              },
              {
                "index": 1,
                "name": "Majestic Manderville",
                "completed": 11,
                "total": 19,
                "percentage": 58
              },
              {
                "index": 2,
                "name": "Amazing Manderville",
                "completed": 11,
                "total": 19,
                "percentage": 58
              },
              {
                "index": 3,
                "name": "Manderville",
                "completed": 11,
                "total": 19,
                "percentage": 58
              }
            ],
            "inProgress": true,
            "isComplete": false
          },
          "dt": {
            "name": "Phantom Weapons",
            "abbr": "Phantom",
            "expansion": "Dawntrail",
            "completed": 0,
            "total": 21,
            "percentage": 0,
            "highestStage": "Umbrae",
            "stages": [
              {
                "index": 0,
                "name": "Obscurum",
                "completed": 0,
                "total": 21,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Umbrae",
                "completed": 4,
                "total": 21,
                "percentage": 19
              },
              {
                "index": 2,
                "name": "Penumbrae",
                "completed": 8,
                "total": 21,
                "percentage": 38
              }
            ],
            "inProgress": true,
            "isComplete": false
          }
        },
        "tools": {
          "lucis": {
            "name": "Lucis Tools",
            "abbr": "Lucis",
            "expansion": "A Realm Reborn",
            "completed": 0,
            "total": 0,
            "percentage": 0,
            "stages": [],
            "highestStage": null,
            "inProgress": false,
            "isComplete": false
          },
          "skysteel": {
            "name": "Skysteel Tools",
            "abbr": "Skysteel",
            "expansion": "Shadowbringers",
            "completed": 4,
            "total": 11,
            "percentage": 36,
            "stages": [
              {
                "index": 0,
                "name": "Skybuilder",
                "completed": 4,
                "total": 11,
                "percentage": 36
              },
              {
                "index": 1,
                "name": "Skysung",
                "completed": 4,
                "total": 11,
                "percentage": 36
              }
            ],
            "highestStage": "Skybuilder",
            "inProgress": true,
            "isComplete": false
          },
          "splendorous": {
            "name": "Splendorous Tools",
            "abbr": "Splendorous",
            "expansion": "Endwalker",
            "completed": 0,
            "total": 11,
            "percentage": 0,
            "stages": [
              {
                "index": 0,
                "name": "Lodestar",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Brilliant",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Crystalline",
                "completed": 1,
                "total": 11,
                "percentage": 9
              }
            ],
            "highestStage": "Crystalline",
            "inProgress": true,
            "isComplete": false
          },
          "cosmic": {
            "name": "Cosmic Tools",
            "abbr": "Cosmic",
            "expansion": "Dawntrail",
            "completed": 11,
            "total": 11,
            "percentage": 100,
            "stages": [
              {
                "index": 0,
                "name": "Hyper",
                "completed": 11,
                "total": 11,
                "percentage": 100
              },
              {
                "index": 1,
                "name": "Stellar",
                "completed": 11,
                "total": 11,
                "percentage": 100
              },
              {
                "index": 2,
                "name": "Cosmic",
                "completed": 11,
                "total": 11,
                "percentage": 100
              }
            ],
            "highestStage": "Hyper",
            "inProgress": true,
            "isComplete": true
          }
        }
      }
    },
    "lastUpdated": "2026-02-12T00:32:55.488Z"
  },
  {
    "id": "24387385",
    "name": "Mira Wa'neko",
    "world": "Zodiark [Light]",
    "image": "https://img2.finalfantasyxiv.com/f/e5de5126497a6bf816908d12fdb2e908_c274370774c6bc3483cc8740805f41bcfl0.jpg?1768583610",
    "jobs": {
      "combat": [
        {
          "name": "White Mage",
          "level": 100,
          "abbr": "WHM"
        },
        {
          "name": "Pictomancer",
          "level": 80,
          "abbr": "PCT"
        },
        {
          "name": "Dancer",
          "level": 60,
          "abbr": "DNC"
        },
        {
          "name": "Blue Mage",
          "level": 6,
          "abbr": "BLU"
        },
        {
          "name": "Gladiator",
          "level": 0,
          "abbr": "GLA"
        },
        {
          "name": "Marauder",
          "level": 0,
          "abbr": "MRD"
        },
        {
          "name": "Dark Knight",
          "level": 0,
          "abbr": "DRK"
        },
        {
          "name": "Gunbreaker",
          "level": 0,
          "abbr": "GNB"
        },
        {
          "name": "Scholar",
          "level": 0,
          "abbr": "SCH"
        },
        {
          "name": "Astrologian",
          "level": 0,
          "abbr": "AST"
        },
        {
          "name": "Sage",
          "level": 0,
          "abbr": "SGE"
        },
        {
          "name": "Pugilist",
          "level": 0,
          "abbr": "PGL"
        },
        {
          "name": "Lancer",
          "level": 0,
          "abbr": "LNC"
        },
        {
          "name": "Rogue",
          "level": 0,
          "abbr": "ROG"
        },
        {
          "name": "Samurai",
          "level": 0,
          "abbr": "SAM"
        },
        {
          "name": "Reaper",
          "level": 0,
          "abbr": "RPR"
        },
        {
          "name": "Viper",
          "level": 0,
          "abbr": "VPR"
        },
        {
          "name": "Archer",
          "level": 0,
          "abbr": "ARC"
        },
        {
          "name": "Machinist",
          "level": 0,
          "abbr": "MCH"
        },
        {
          "name": "Thaumaturge",
          "level": 0,
          "abbr": "THM"
        },
        {
          "name": "Arcanist",
          "level": 0,
          "abbr": "ACN"
        },
        {
          "name": "Red Mage",
          "level": 0,
          "abbr": "RDM"
        }
      ],
      "crafters": [
        {
          "name": "Carpenter",
          "level": 100,
          "abbr": "CRP"
        },
        {
          "name": "Blacksmith",
          "level": 100,
          "abbr": "BSM"
        },
        {
          "name": "Armorer",
          "level": 100,
          "abbr": "ARM"
        },
        {
          "name": "Culinarian",
          "level": 100,
          "abbr": "CUL"
        },
        {
          "name": "Goldsmith",
          "level": 84,
          "abbr": "GSM"
        },
        {
          "name": "Leatherworker",
          "level": 61,
          "abbr": "LTW"
        },
        {
          "name": "Weaver",
          "level": 60,
          "abbr": "WVR"
        },
        {
          "name": "Alchemist",
          "level": 50,
          "abbr": "ALC"
        }
      ],
      "gatherers": [
        {
          "name": "Miner",
          "level": 100,
          "abbr": "MIN"
        },
        {
          "name": "Botanist",
          "level": 100,
          "abbr": "BTN"
        },
        {
          "name": "Fisher",
          "level": 6,
          "abbr": "FSH"
        }
      ],
      "phantom": [
        {
          "name": "Phantom Bard",
          "level": 2,
          "abbr": "Bard"
        },
        {
          "name": "Phantom Knight",
          "level": 1,
          "abbr": "Knight"
        },
        {
          "name": "Phantom Monk",
          "level": 1,
          "abbr": "Monk"
        },
        {
          "name": "Phantom Freelancer",
          "level": 1,
          "abbr": "Freelancer"
        }
      ]
    },
    "achievements": {
      "allScore": 4415,
      "baseScore": 4280,
      "relics": {
        "weapons": {
          "arr": {
            "name": "Zodiac Weapons",
            "abbr": "Zodiac",
            "expansion": "A Realm Reborn",
            "completed": 0,
            "total": 13,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Zodiac Zeta",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Zodiac",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Nexus",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Novus",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 4,
                "name": "Animus",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 5,
                "name": "Zodarc",
                "completed": 0,
                "total": 13,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "hw": {
            "name": "Anima Weapons",
            "abbr": "Anima",
            "expansion": "Heavensward",
            "completed": 0,
            "total": 13,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Lux",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Complete",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Sharpened",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Reconditioned",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 4,
                "name": "Hyperconductive",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 5,
                "name": "Anima",
                "completed": 0,
                "total": 13,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "sb": {
            "name": "Eureka Weapons",
            "abbr": "Eureka",
            "expansion": "Stormblood",
            "completed": 0,
            "total": 15,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Eureka",
                "completed": 0,
                "total": 15,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Pyros",
                "completed": 0,
                "total": 15,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Elemental",
                "completed": 0,
                "total": 15,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Anemos",
                "completed": 0,
                "total": 15,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "shb": {
            "name": "Resistance Weapons",
            "abbr": "Resistance",
            "expansion": "Shadowbringers",
            "completed": 0,
            "total": 17,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Blade's",
                "completed": 0,
                "total": 17,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Law's Order",
                "completed": 0,
                "total": 17,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Recollection",
                "completed": 0,
                "total": 17,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Resistance",
                "completed": 0,
                "total": 17,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "ew": {
            "name": "Manderville Weapons",
            "abbr": "Manderville",
            "expansion": "Endwalker",
            "completed": 0,
            "total": 19,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Mandervillous",
                "completed": 0,
                "total": 19,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Majestic Manderville",
                "completed": 0,
                "total": 19,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Amazing Manderville",
                "completed": 0,
                "total": 19,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Manderville",
                "completed": 0,
                "total": 19,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "dt": {
            "name": "Phantom Weapons",
            "abbr": "Phantom",
            "expansion": "Dawntrail",
            "completed": 0,
            "total": 21,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Obscurum",
                "completed": 0,
                "total": 21,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Umbrae",
                "completed": 0,
                "total": 21,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Penumbrae",
                "completed": 0,
                "total": 21,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          }
        },
        "tools": {
          "lucis": {
            "name": "Lucis Tools",
            "abbr": "Lucis",
            "expansion": "A Realm Reborn",
            "completed": 0,
            "total": 0,
            "percentage": 0,
            "stages": [],
            "highestStage": null,
            "inProgress": false,
            "isComplete": false
          },
          "skysteel": {
            "name": "Skysteel Tools",
            "abbr": "Skysteel",
            "expansion": "Shadowbringers",
            "completed": 0,
            "total": 11,
            "percentage": 0,
            "stages": [
              {
                "index": 0,
                "name": "Skybuilder",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Skysung",
                "completed": 0,
                "total": 11,
                "percentage": 0
              }
            ],
            "highestStage": null,
            "inProgress": false,
            "isComplete": false
          },
          "splendorous": {
            "name": "Splendorous Tools",
            "abbr": "Splendorous",
            "expansion": "Endwalker",
            "completed": 0,
            "total": 11,
            "percentage": 0,
            "stages": [
              {
                "index": 0,
                "name": "Lodestar",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Brilliant",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Crystalline",
                "completed": 0,
                "total": 11,
                "percentage": 0
              }
            ],
            "highestStage": null,
            "inProgress": false,
            "isComplete": false
          },
          "cosmic": {
            "name": "Cosmic Tools",
            "abbr": "Cosmic",
            "expansion": "Dawntrail",
            "completed": 0,
            "total": 11,
            "percentage": 0,
            "stages": [
              {
                "index": 0,
                "name": "Hyper",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Stellar",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Cosmic",
                "completed": 7,
                "total": 11,
                "percentage": 64
              }
            ],
            "highestStage": "Cosmic",
            "inProgress": true,
            "isComplete": false
          }
        }
      }
    },
    "lastUpdated": "2026-02-14T00:32:45.616Z"
  }
];

export default characterData;
