// Auto-generated by update-characters.js

const characterData = [
  {
    "id": "24921505",
    "name": "Mira Wa'neko",
    "world": "Diabolos [Crystal]",
    "image": "https://img2.finalfantasyxiv.com/f/7c13a0269a6d7953946aff5be6ecff69_7b33d33ae3ecb996f778a5f67a6a0af6fl0.jpg",
    "jobs": {
      "combat": [
        {
          "name": "Gunbreaker",
          "level": 100,
          "abbr": "GNB"
        },
        {
          "name": "White Mage",
          "level": 100,
          "abbr": "WHM"
        },
        {
          "name": "Scholar",
          "level": 100,
          "abbr": "SCH"
        },
        {
          "name": "Astrologian",
          "level": 100,
          "abbr": "AST"
        },
        {
          "name": "Sage",
          "level": 100,
          "abbr": "SGE"
        },
        {
          "name": "Dragoon",
          "level": 100,
          "abbr": "DRG"
        },
        {
          "name": "Ninja",
          "level": 100,
          "abbr": "NIN"
        },
        {
          "name": "Reaper",
          "level": 100,
          "abbr": "RPR"
        },
        {
          "name": "Viper",
          "level": 100,
          "abbr": "VPR"
        },
        {
          "name": "Bard",
          "level": 100,
          "abbr": "BRD"
        },
        {
          "name": "Dancer",
          "level": 100,
          "abbr": "DNC"
        },
        {
          "name": "Black Mage",
          "level": 100,
          "abbr": "BLM"
        },
        {
          "name": "Summoner",
          "level": 100,
          "abbr": "SMN"
        },
        {
          "name": "Red Mage",
          "level": 100,
          "abbr": "RDM"
        },
        {
          "name": "Pictomancer",
          "level": 100,
          "abbr": "PCT"
        },
        {
          "name": "Blue Mage",
          "level": 70,
          "abbr": "BLU"
        },
        {
          "name": "Paladin",
          "level": 55,
          "abbr": "PLD"
        },
        {
          "name": "Warrior",
          "level": 55,
          "abbr": "WAR"
        },
        {
          "name": "Samurai",
          "level": 51,
          "abbr": "SAM"
        },
        {
          "name": "Pugilist",
          "level": 21,
          "abbr": "PGL"
        }
      ],
      "crafters": [
        {
          "name": "Carpenter",
          "level": 100,
          "abbr": "CRP"
        },
        {
          "name": "Blacksmith",
          "level": 100,
          "abbr": "BSM"
        },
        {
          "name": "Armorer",
          "level": 100,
          "abbr": "ARM"
        },
        {
          "name": "Goldsmith",
          "level": 100,
          "abbr": "GSM"
        },
        {
          "name": "Leatherworker",
          "level": 100,
          "abbr": "LTW"
        },
        {
          "name": "Weaver",
          "level": 100,
          "abbr": "WVR"
        },
        {
          "name": "Alchemist",
          "level": 100,
          "abbr": "ALC"
        },
        {
          "name": "Culinarian",
          "level": 100,
          "abbr": "CUL"
        }
      ],
      "gatherers": [
        {
          "name": "Miner",
          "level": 100,
          "abbr": "MIN"
        },
        {
          "name": "Botanist",
          "level": 100,
          "abbr": "BTN"
        },
        {
          "name": "Fisher",
          "level": 100,
          "abbr": "FSH"
        }
      ],
      "phantom": [
        {
          "name": "Phantom Freelancer",
          "level": 10,
          "abbr": "Freelancer"
        },
        {
          "name": "Phantom Knight",
          "level": 6,
          "abbr": "Knight"
        },
        {
          "name": "Phantom Monk",
          "level": 6,
          "abbr": "Monk"
        },
        {
          "name": "Phantom Cannoneer",
          "level": 6,
          "abbr": "Cannoneer"
        },
        {
          "name": "Phantom Time Mage",
          "level": 5,
          "abbr": "Time Mage"
        },
        {
          "name": "Phantom Oracle",
          "level": 5,
          "abbr": "Oracle"
        },
        {
          "name": "Phantom Chemist",
          "level": 4,
          "abbr": "Chemist"
        },
        {
          "name": "Phantom Geomancer",
          "level": 4,
          "abbr": "Geomancer"
        },
        {
          "name": "Phantom Bard",
          "level": 4,
          "abbr": "Bard"
        },
        {
          "name": "Phantom Dancer",
          "level": 4,
          "abbr": "Dancer"
        },
        {
          "name": "Phantom Berserker",
          "level": 3,
          "abbr": "Berserker"
        },
        {
          "name": "Phantom Thief",
          "level": 1,
          "abbr": "Thief"
        },
        {
          "name": "Phantom Samurai",
          "level": 1,
          "abbr": "Samurai"
        },
        {
          "name": "Phantom Ranger",
          "level": 1,
          "abbr": "Ranger"
        },
        {
          "name": "Phantom Mystic Knight",
          "level": 1,
          "abbr": "Mystic Knight"
        },
        {
          "name": "Phantom Gladiator",
          "level": 1,
          "abbr": "Gladiator"
        }
      ]
    },
    "achievements": {
      "allScore": 16860,
      "baseScore": 15885,
      "relics": {
        "weapons": {
          "arr": {
            "name": "Zodiac Weapons",
            "abbr": "Zodiac",
            "expansion": "A Realm Reborn",
            "completed": 7,
            "total": 13,
            "percentage": 54,
            "highestStage": "Zodiac Zeta",
            "stages": [
              {
                "index": 0,
                "name": "Zodiac Zeta",
                "completed": 1,
                "total": 1,
                "percentage": 100
              },
              {
                "index": 1,
                "name": "Zodiac",
                "completed": 1,
                "total": 1,
                "percentage": 100
              },
              {
                "index": 2,
                "name": "Nexus",
                "completed": 1,
                "total": 1,
                "percentage": 100
              },
              {
                "index": 3,
                "name": "Novus",
                "completed": 1,
                "total": 1,
                "percentage": 100
              },
              {
                "index": 4,
                "name": "Animus",
                "completed": 1,
                "total": 1,
                "percentage": 100
              },
              {
                "index": 5,
                "name": "Zodarc",
                "completed": 7,
                "total": 13,
                "percentage": 54
              }
            ],
            "inProgress": true,
            "isComplete": false
          },
          "hw": {
            "name": "Anima Weapons",
            "abbr": "Anima",
            "expansion": "Heavensward",
            "completed": 1,
            "total": 13,
            "percentage": 8,
            "highestStage": "Lux",
            "stages": [
              {
                "index": 0,
                "name": "Lux",
                "completed": 1,
                "total": 13,
                "percentage": 8
              },
              {
                "index": 1,
                "name": "Complete",
                "completed": 1,
                "total": 13,
                "percentage": 8
              },
              {
                "index": 2,
                "name": "Sharpened",
                "completed": 1,
                "total": 13,
                "percentage": 8
              },
              {
                "index": 3,
                "name": "Reconditioned",
                "completed": 1,
                "total": 13,
                "percentage": 8
              },
              {
                "index": 4,
                "name": "Hyperconductive",
                "completed": 1,
                "total": 13,
                "percentage": 8
              },
              {
                "index": 5,
                "name": "Anima",
                "completed": 1,
                "total": 13,
                "percentage": 8
              }
            ],
            "inProgress": true,
            "isComplete": false
          },
          "sb": {
            "name": "Eureka Weapons",
            "abbr": "Eureka",
            "expansion": "Stormblood",
            "completed": 0,
            "total": 15,
            "percentage": 0,
            "highestStage": "Elemental",
            "stages": [
              {
                "index": 0,
                "name": "Eureka",
                "completed": 0,
                "total": 15,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Pyros",
                "completed": 0,
                "total": 15,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Elemental",
                "completed": 1,
                "total": 15,
                "percentage": 7
              },
              {
                "index": 3,
                "name": "Anemos",
                "completed": 1,
                "total": 15,
                "percentage": 7
              }
            ],
            "inProgress": true,
            "isComplete": false
          },
          "shb": {
            "name": "Resistance Weapons",
            "abbr": "Resistance",
            "expansion": "Shadowbringers",
            "completed": 1,
            "total": 17,
            "percentage": 6,
            "highestStage": "Blade's",
            "stages": [
              {
                "index": 0,
                "name": "Blade's",
                "completed": 1,
                "total": 17,
                "percentage": 6
              },
              {
                "index": 1,
                "name": "Law's Order",
                "completed": 2,
                "total": 17,
                "percentage": 12
              },
              {
                "index": 2,
                "name": "Recollection",
                "completed": 2,
                "total": 17,
                "percentage": 12
              },
              {
                "index": 3,
                "name": "Resistance",
                "completed": 4,
                "total": 17,
                "percentage": 24
              }
            ],
            "inProgress": true,
            "isComplete": false
          },
          "ew": {
            "name": "Manderville Weapons",
            "abbr": "Manderville",
            "expansion": "Endwalker",
            "completed": 11,
            "total": 19,
            "percentage": 58,
            "highestStage": "Mandervillous",
            "stages": [
              {
                "index": 0,
                "name": "Mandervillous",
                "completed": 11,
                "total": 19,
                "percentage": 58
              },
              {
                "index": 1,
                "name": "Majestic Manderville",
                "completed": 11,
                "total": 19,
                "percentage": 58
              },
              {
                "index": 2,
                "name": "Amazing Manderville",
                "completed": 12,
                "total": 19,
                "percentage": 63
              },
              {
                "index": 3,
                "name": "Manderville",
                "completed": 12,
                "total": 19,
                "percentage": 63
              }
            ],
            "inProgress": true,
            "isComplete": false
          },
          "dt": {
            "name": "Phantom Weapons",
            "abbr": "Phantom",
            "expansion": "Dawntrail",
            "completed": 0,
            "total": 21,
            "percentage": 0,
            "highestStage": "Umbrae",
            "stages": [
              {
                "index": 0,
                "name": "Obscurum",
                "completed": 0,
                "total": 21,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Umbrae",
                "completed": 8,
                "total": 21,
                "percentage": 38
              },
              {
                "index": 2,
                "name": "Penumbrae",
                "completed": 8,
                "total": 21,
                "percentage": 38
              }
            ],
            "inProgress": true,
            "isComplete": false
          }
        },
        "tools": {
          "lucis": {
            "name": "Lucis Tools",
            "abbr": "Lucis",
            "expansion": "A Realm Reborn",
            "completed": 0,
            "total": 0,
            "percentage": 0,
            "stages": [],
            "highestStage": null,
            "inProgress": false,
            "isComplete": false
          },
          "skysteel": {
            "name": "Skysteel Tools",
            "abbr": "Skysteel",
            "expansion": "Shadowbringers",
            "completed": 5,
            "total": 11,
            "percentage": 45,
            "stages": [
              {
                "index": 0,
                "name": "Skybuilder",
                "completed": 5,
                "total": 11,
                "percentage": 45
              },
              {
                "index": 1,
                "name": "Skysung",
                "completed": 5,
                "total": 11,
                "percentage": 45
              }
            ],
            "highestStage": "Skybuilder",
            "inProgress": true,
            "isComplete": false
          },
          "splendorous": {
            "name": "Splendorous Tools",
            "abbr": "Splendorous",
            "expansion": "Endwalker",
            "completed": 1,
            "total": 11,
            "percentage": 9,
            "stages": [
              {
                "index": 0,
                "name": "Lodestar",
                "completed": 1,
                "total": 11,
                "percentage": 9
              },
              {
                "index": 1,
                "name": "Brilliant",
                "completed": 1,
                "total": 11,
                "percentage": 9
              },
              {
                "index": 2,
                "name": "Crystalline",
                "completed": 1,
                "total": 11,
                "percentage": 9
              }
            ],
            "highestStage": "Lodestar",
            "inProgress": true,
            "isComplete": false
          },
          "cosmic": {
            "name": "Cosmic Tools",
            "abbr": "Cosmic",
            "expansion": "Dawntrail",
            "completed": 11,
            "total": 11,
            "percentage": 100,
            "stages": [
              {
                "index": 0,
                "name": "Stars",
                "completed": 11,
                "total": 11,
                "percentage": 100
              },
              {
                "index": 1,
                "name": "Hyper",
                "completed": 11,
                "total": 11,
                "percentage": 100
              },
              {
                "index": 2,
                "name": "Stellar",
                "completed": 11,
                "total": 11,
                "percentage": 100
              },
              {
                "index": 3,
                "name": "Cosmic",
                "completed": 11,
                "total": 11,
                "percentage": 100
              }
            ],
            "highestStage": "Stars",
            "inProgress": true,
            "isComplete": true
          }
        }
      },
      "exploration": {
        "completed": 176,
        "total": 184,
        "percentage": 96
      },
      "msq": {
        "completed": 75,
        "total": 75,
        "percentage": 100,
        "patches": [
          {
            "patch": "2.0",
            "completed": 7,
            "total": 7,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "2.2",
            "completed": 2,
            "total": 2,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "2.3",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "2.4",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "2.55",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.0",
            "completed": 7,
            "total": 7,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.1",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.2",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.3",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.4",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.5",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.56",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.0",
            "completed": 8,
            "total": 8,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.1",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.2",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.3",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.4",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.5",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.56",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.0",
            "completed": 6,
            "total": 6,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.1",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.2",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.3",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.4",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.5",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.55",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.0",
            "completed": 7,
            "total": 7,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.1",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.2",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.3",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.4",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.5",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.55",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "7.0",
            "completed": 6,
            "total": 6,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "7.1",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "7.2",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "7.3",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "7.4",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "7.5",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          }
        ]
      },
      "raids": {
        "completed": 44,
        "total": 63,
        "percentage": 70
      },
      "firstEarnedAt": "2019-04-11T15:03:45.000Z",
      "latestEarnedAt": "2026-07-23T15:02:53.000Z"
    },
    "lastUpdated": "2026-07-24T02:42:33.303Z"
  },
  {
    "id": "24387385",
    "name": "Mira Wa'neko",
    "world": "Maduin [Dynamis]",
    "image": "https://img2.finalfantasyxiv.com/f/e5de5126497a6bf816908d12fdb2e908_7ff236346f6151d8a2c08fd0b4a0b806fl0.jpg",
    "jobs": {
      "combat": [
        {
          "name": "White Mage",
          "level": 100,
          "abbr": "WHM"
        },
        {
          "name": "Dancer",
          "level": 90,
          "abbr": "DNC"
        },
        {
          "name": "Pictomancer",
          "level": 80,
          "abbr": "PCT"
        },
        {
          "name": "Blue Mage",
          "level": 6,
          "abbr": "BLU"
        }
      ],
      "crafters": [
        {
          "name": "Carpenter",
          "level": 100,
          "abbr": "CRP"
        },
        {
          "name": "Blacksmith",
          "level": 100,
          "abbr": "BSM"
        },
        {
          "name": "Armorer",
          "level": 100,
          "abbr": "ARM"
        },
        {
          "name": "Goldsmith",
          "level": 100,
          "abbr": "GSM"
        },
        {
          "name": "Leatherworker",
          "level": 100,
          "abbr": "LTW"
        },
        {
          "name": "Weaver",
          "level": 100,
          "abbr": "WVR"
        },
        {
          "name": "Alchemist",
          "level": 100,
          "abbr": "ALC"
        },
        {
          "name": "Culinarian",
          "level": 100,
          "abbr": "CUL"
        }
      ],
      "gatherers": [
        {
          "name": "Miner",
          "level": 100,
          "abbr": "MIN"
        },
        {
          "name": "Botanist",
          "level": 100,
          "abbr": "BTN"
        },
        {
          "name": "Fisher",
          "level": 100,
          "abbr": "FSH"
        }
      ],
      "phantom": [
        {
          "name": "Phantom Bard",
          "level": 2,
          "abbr": "Bard"
        },
        {
          "name": "Phantom Knight",
          "level": 1,
          "abbr": "Knight"
        },
        {
          "name": "Phantom Monk",
          "level": 1,
          "abbr": "Monk"
        },
        {
          "name": "Phantom Freelancer",
          "level": 1,
          "abbr": "Freelancer"
        }
      ]
    },
    "achievements": {
      "allScore": 5645,
      "baseScore": 5480,
      "relics": {
        "weapons": {
          "arr": {
            "name": "Zodiac Weapons",
            "abbr": "Zodiac",
            "expansion": "A Realm Reborn",
            "completed": 0,
            "total": 13,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Zodiac Zeta",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Zodiac",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Nexus",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Novus",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 4,
                "name": "Animus",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 5,
                "name": "Zodarc",
                "completed": 0,
                "total": 13,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "hw": {
            "name": "Anima Weapons",
            "abbr": "Anima",
            "expansion": "Heavensward",
            "completed": 0,
            "total": 13,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Lux",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Complete",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Sharpened",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Reconditioned",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 4,
                "name": "Hyperconductive",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 5,
                "name": "Anima",
                "completed": 0,
                "total": 13,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "sb": {
            "name": "Eureka Weapons",
            "abbr": "Eureka",
            "expansion": "Stormblood",
            "completed": 0,
            "total": 15,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Eureka",
                "completed": 0,
                "total": 15,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Pyros",
                "completed": 0,
                "total": 15,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Elemental",
                "completed": 0,
                "total": 15,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Anemos",
                "completed": 0,
                "total": 15,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "shb": {
            "name": "Resistance Weapons",
            "abbr": "Resistance",
            "expansion": "Shadowbringers",
            "completed": 0,
            "total": 17,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Blade's",
                "completed": 0,
                "total": 17,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Law's Order",
                "completed": 0,
                "total": 17,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Recollection",
                "completed": 0,
                "total": 17,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Resistance",
                "completed": 0,
                "total": 17,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "ew": {
            "name": "Manderville Weapons",
            "abbr": "Manderville",
            "expansion": "Endwalker",
            "completed": 0,
            "total": 19,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Mandervillous",
                "completed": 0,
                "total": 19,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Majestic Manderville",
                "completed": 0,
                "total": 19,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Amazing Manderville",
                "completed": 0,
                "total": 19,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Manderville",
                "completed": 0,
                "total": 19,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "dt": {
            "name": "Phantom Weapons",
            "abbr": "Phantom",
            "expansion": "Dawntrail",
            "completed": 0,
            "total": 21,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Obscurum",
                "completed": 0,
                "total": 21,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Umbrae",
                "completed": 0,
                "total": 21,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Penumbrae",
                "completed": 0,
                "total": 21,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          }
        },
        "tools": {
          "lucis": {
            "name": "Lucis Tools",
            "abbr": "Lucis",
            "expansion": "A Realm Reborn",
            "completed": 0,
            "total": 0,
            "percentage": 0,
            "stages": [],
            "highestStage": null,
            "inProgress": false,
            "isComplete": false
          },
          "skysteel": {
            "name": "Skysteel Tools",
            "abbr": "Skysteel",
            "expansion": "Shadowbringers",
            "completed": 0,
            "total": 11,
            "percentage": 0,
            "stages": [
              {
                "index": 0,
                "name": "Skybuilder",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Skysung",
                "completed": 0,
                "total": 11,
                "percentage": 0
              }
            ],
            "highestStage": null,
            "inProgress": false,
            "isComplete": false
          },
          "splendorous": {
            "name": "Splendorous Tools",
            "abbr": "Splendorous",
            "expansion": "Endwalker",
            "completed": 0,
            "total": 11,
            "percentage": 0,
            "stages": [
              {
                "index": 0,
                "name": "Lodestar",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Brilliant",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Crystalline",
                "completed": 0,
                "total": 11,
                "percentage": 0
              }
            ],
            "highestStage": null,
            "inProgress": false,
            "isComplete": false
          },
          "cosmic": {
            "name": "Cosmic Tools",
            "abbr": "Cosmic",
            "expansion": "Dawntrail",
            "completed": 10,
            "total": 11,
            "percentage": 91,
            "stages": [
              {
                "index": 0,
                "name": "Stars",
                "completed": 10,
                "total": 11,
                "percentage": 91
              },
              {
                "index": 1,
                "name": "Hyper",
                "completed": 11,
                "total": 11,
                "percentage": 100
              },
              {
                "index": 2,
                "name": "Stellar",
                "completed": 11,
                "total": 11,
                "percentage": 100
              },
              {
                "index": 3,
                "name": "Cosmic",
                "completed": 11,
                "total": 11,
                "percentage": 100
              }
            ],
            "highestStage": "Stars",
            "inProgress": true,
            "isComplete": false
          }
        }
      },
      "exploration": {
        "completed": 89,
        "total": 184,
        "percentage": 48
      },
      "msq": {
        "completed": 74,
        "total": 75,
        "percentage": 99,
        "patches": [
          {
            "patch": "2.0",
            "completed": 7,
            "total": 7,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "2.2",
            "completed": 2,
            "total": 2,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "2.3",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "2.4",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "2.55",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.0",
            "completed": 7,
            "total": 7,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.1",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.2",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.3",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.4",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.5",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "3.56",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.0",
            "completed": 8,
            "total": 8,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.1",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.2",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.3",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.4",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.5",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "4.56",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.0",
            "completed": 6,
            "total": 6,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.1",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.2",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.3",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.4",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.5",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "5.55",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.0",
            "completed": 7,
            "total": 7,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.1",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.2",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.3",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.4",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.5",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "6.55",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "7.0",
            "completed": 6,
            "total": 6,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "7.1",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "7.2",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "7.3",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "7.4",
            "completed": 1,
            "total": 1,
            "percentage": 100,
            "isCurrent": false
          },
          {
            "patch": "7.5",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": true
          }
        ]
      },
      "raids": {
        "completed": 17,
        "total": 63,
        "percentage": 27
      },
      "firstEarnedAt": "2019-02-25T22:55:07.000Z",
      "latestEarnedAt": "2026-07-22T09:25:02.000Z"
    },
    "lastUpdated": "2026-07-22T21:12:28.851Z"
  },
  {
    "id": "61617093",
    "name": "Mira Wa'neko",
    "world": "Alpha [Light]",
    "image": "https://img2.finalfantasyxiv.com/f/d39f7f955a5293dd1937567ec64c269a_6132295fcf5570fb8b0a944ef322a598fl0.jpg",
    "jobs": {
      "combat": [
        {
          "name": "White Mage",
          "level": 90,
          "abbr": "WHM"
        }
      ],
      "crafters": [],
      "gatherers": [],
      "phantom": []
    },
    "achievements": {
      "allScore": 350,
      "baseScore": 345,
      "relics": {
        "weapons": {
          "arr": {
            "name": "Zodiac Weapons",
            "abbr": "Zodiac",
            "expansion": "A Realm Reborn",
            "completed": 0,
            "total": 13,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Zodiac Zeta",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Zodiac",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Nexus",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Novus",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 4,
                "name": "Animus",
                "completed": 0,
                "total": 1,
                "percentage": 0
              },
              {
                "index": 5,
                "name": "Zodarc",
                "completed": 0,
                "total": 13,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "hw": {
            "name": "Anima Weapons",
            "abbr": "Anima",
            "expansion": "Heavensward",
            "completed": 0,
            "total": 13,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Lux",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Complete",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Sharpened",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Reconditioned",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 4,
                "name": "Hyperconductive",
                "completed": 0,
                "total": 13,
                "percentage": 0
              },
              {
                "index": 5,
                "name": "Anima",
                "completed": 0,
                "total": 13,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "sb": {
            "name": "Eureka Weapons",
            "abbr": "Eureka",
            "expansion": "Stormblood",
            "completed": 0,
            "total": 15,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Eureka",
                "completed": 0,
                "total": 15,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Pyros",
                "completed": 0,
                "total": 15,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Elemental",
                "completed": 0,
                "total": 15,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Anemos",
                "completed": 0,
                "total": 15,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "shb": {
            "name": "Resistance Weapons",
            "abbr": "Resistance",
            "expansion": "Shadowbringers",
            "completed": 0,
            "total": 17,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Blade's",
                "completed": 0,
                "total": 17,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Law's Order",
                "completed": 0,
                "total": 17,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Recollection",
                "completed": 0,
                "total": 17,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Resistance",
                "completed": 0,
                "total": 17,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "ew": {
            "name": "Manderville Weapons",
            "abbr": "Manderville",
            "expansion": "Endwalker",
            "completed": 0,
            "total": 19,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Mandervillous",
                "completed": 0,
                "total": 19,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Majestic Manderville",
                "completed": 0,
                "total": 19,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Amazing Manderville",
                "completed": 0,
                "total": 19,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Manderville",
                "completed": 0,
                "total": 19,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          },
          "dt": {
            "name": "Phantom Weapons",
            "abbr": "Phantom",
            "expansion": "Dawntrail",
            "completed": 0,
            "total": 21,
            "percentage": 0,
            "highestStage": null,
            "stages": [
              {
                "index": 0,
                "name": "Obscurum",
                "completed": 0,
                "total": 21,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Umbrae",
                "completed": 0,
                "total": 21,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Penumbrae",
                "completed": 0,
                "total": 21,
                "percentage": 0
              }
            ],
            "inProgress": false,
            "isComplete": false
          }
        },
        "tools": {
          "lucis": {
            "name": "Lucis Tools",
            "abbr": "Lucis",
            "expansion": "A Realm Reborn",
            "completed": 0,
            "total": 0,
            "percentage": 0,
            "stages": [],
            "highestStage": null,
            "inProgress": false,
            "isComplete": false
          },
          "skysteel": {
            "name": "Skysteel Tools",
            "abbr": "Skysteel",
            "expansion": "Shadowbringers",
            "completed": 0,
            "total": 11,
            "percentage": 0,
            "stages": [
              {
                "index": 0,
                "name": "Skybuilder",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Skysung",
                "completed": 0,
                "total": 11,
                "percentage": 0
              }
            ],
            "highestStage": null,
            "inProgress": false,
            "isComplete": false
          },
          "splendorous": {
            "name": "Splendorous Tools",
            "abbr": "Splendorous",
            "expansion": "Endwalker",
            "completed": 0,
            "total": 11,
            "percentage": 0,
            "stages": [
              {
                "index": 0,
                "name": "Lodestar",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Brilliant",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Crystalline",
                "completed": 0,
                "total": 11,
                "percentage": 0
              }
            ],
            "highestStage": null,
            "inProgress": false,
            "isComplete": false
          },
          "cosmic": {
            "name": "Cosmic Tools",
            "abbr": "Cosmic",
            "expansion": "Dawntrail",
            "completed": 0,
            "total": 11,
            "percentage": 0,
            "stages": [
              {
                "index": 0,
                "name": "Stars",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 1,
                "name": "Hyper",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 2,
                "name": "Stellar",
                "completed": 0,
                "total": 11,
                "percentage": 0
              },
              {
                "index": 3,
                "name": "Cosmic",
                "completed": 0,
                "total": 11,
                "percentage": 0
              }
            ],
            "highestStage": null,
            "inProgress": false,
            "isComplete": false
          }
        }
      },
      "exploration": {
        "completed": 19,
        "total": 184,
        "percentage": 10
      },
      "msq": {
        "completed": 4,
        "total": 75,
        "percentage": 5,
        "patches": [
          {
            "patch": "2.0",
            "completed": 4,
            "total": 7,
            "percentage": 57,
            "isCurrent": true
          },
          {
            "patch": "2.2",
            "completed": 0,
            "total": 2,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "2.3",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "2.4",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "2.55",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "3.0",
            "completed": 0,
            "total": 7,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "3.1",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "3.2",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "3.3",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "3.4",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "3.5",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "3.56",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "4.0",
            "completed": 0,
            "total": 8,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "4.1",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "4.2",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "4.3",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "4.4",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "4.5",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "4.56",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "5.0",
            "completed": 0,
            "total": 6,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "5.1",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "5.2",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "5.3",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "5.4",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "5.5",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "5.55",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "6.0",
            "completed": 0,
            "total": 7,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "6.1",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "6.2",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "6.3",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "6.4",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "6.5",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "6.55",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "7.0",
            "completed": 0,
            "total": 6,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "7.1",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "7.2",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "7.3",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "7.4",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          },
          {
            "patch": "7.5",
            "completed": 0,
            "total": 1,
            "percentage": 0,
            "isCurrent": false
          }
        ]
      },
      "raids": {
        "completed": 0,
        "total": 63,
        "percentage": 0
      },
      "firstEarnedAt": "2026-07-12T12:48:32.000Z",
      "latestEarnedAt": "2026-07-22T19:33:54.000Z"
    },
    "lastUpdated": "2026-07-22T21:12:33.294Z"
  }
];

export default characterData;
